export const LANG_MAP: Record<string, string> = {
  
  ts:'typescript',tsx:'typescript',mts:'typescript',cts:'typescript',
  js:'javascript',jsx:'javascript',mjs:'javascript',cjs:'javascript',
  html:'html',htm:'html',xhtml:'html',
  css:'css',scss:'scss',less:'less',
  json:'json',jsonc:'json',json5:'json',
  
  c:'c',h:'c',
  cpp:'cpp',cc:'cpp',cxx:'cpp',hpp:'cpp',hxx:'cpp',hh:'cpp',
  cs:'csharp',
  rs:'rust',
  go:'go',
  java:'java',
  kt:'kotlin',kts:'kotlin',
  swift:'swift',
  m:'objective-c',mm:'objective-c',
  
  py:'python',pyw:'python',pyi:'python',
  rb:'ruby',rake:'ruby',gemspec:'ruby',
  php:'php',phtml:'php',php3:'php',php4:'php',php5:'php',
  pl:'perl',pm:'perl',
  lua:'lua',
  r:'r',rmd:'r',
  dart:'dart',
  groovy:'groovy',gvy:'groovy',gy:'groovy',gsh:'groovy',
  scala:'scala',sc:'scala',
  
  sh:'shell',bash:'shell',zsh:'shell',fish:'shell',
  ps1:'powershell',psm1:'powershell',psd1:'powershell',
  bat:'bat',cmd:'bat',
  
  yaml:'yaml',yml:'yaml',
  toml:'toml',
  xml:'xml',xsl:'xml',xslt:'xml',svg:'xml',plist:'xml',csproj:'xml',vbproj:'xml',
  sql:'sql',mysql:'sql',pgsql:'sql',
  graphql:'graphql',gql:'graphql',
  proto:'protobuf',
  ini:'ini',cfg:'ini',conf:'ini',
  env:'ini',
  
  md:'markdown',mdx:'markdown',markdown:'markdown',
  tex:'latex',sty:'latex',cls:'latex',
  rst:'restructuredtext',
  
  clj:'clojure',cljs:'clojure',cljc:'clojure',
  ex:'elixir',exs:'elixir',
  erl:'erlang',hrl:'erlang',
  fs:'fsharp',fsi:'fsharp',fsx:'fsharp',
  hs:'haskell',lhs:'haskell',
  ml:'ocaml',mli:'mli',
  
  vb:'vb',vbs:'vb',
  pas:'pascal',pp:'pascal',
  asm:'asm',s:'asm',
  coffee:'coffeescript',
  tf:'hcl',hcl:'hcl',
  dockerfile:'dockerfile',
  
  abap:'abap',
  apex:'apex',
  azcli:'azcli',
  bicep:'bicep',
  cameligo:'cameligo',
  cypher:'cypher',
  ecl:'ecl',
  flow9:'flow9',
  freemarker2:'freemarker2',
  jinja:'jinja',
  julia:'julia',jl:'julia',
  lexon:'lexon',
  liquid:'liquid',
  m3:'m3',
  msdax:'msdax',
  nb:'nb',
  pascaligo:'pascaligo',

  postiats:'postiats',
  powerquery:'powerquery',pq:'powerquery',
  qsharp:'qsharp',qs:'qsharp',
  razor:'razor',cshtml:'razor',
  redis:'redis',
  redshift:'redshift',
  scheme:'scheme',scm:'scheme',
  solidity:'sol',sol:'sol',
  sophia:'aes',
  sparql:'sparql',
  st:'st',
  systemverilog:'systemverilog',sv:'systemverilog',svh:'systemverilog',
  tcl:'tcl',
  twig:'twig',
  typespec:'typespec',tsp:'typespec',
  verilog:'verilog',v:'verilog',
  wgsl:'wgsl',
};
export const getLang = (filePath: string) => LANG_MAP[filePath.split('.').pop()?.toLowerCase() || ''] || 'plaintext';

