import type { Workspace, Conversation, Message, ToolCall, UIMessage, AgentChunk, AgentInitConfig, BudgetInfo, ModelDef } from './ipc/types';
import type { StoredSession } from './auth';
type ElectronAPI = {
  getZoomFactor: () => number;
  getUserDataPath: () => Promise<string>;
  gcpBase: string;
  anonKey: string;
  getWorkspaces: () => Promise<Workspace[]>;
  createWorkspace: (w: Workspace) => Promise<Workspace>;
  deleteWorkspace: (id: string) => Promise<void>;
  getConversations: (wsId: string | null) => Promise<Conversation[]>;
  createConversation: (c: Conversation) => Promise<Conversation>;
  updateConversation: (id: string, patch: Partial<Conversation>) => Promise<void>;
  deleteConversation: (id: string) => Promise<void>;
  getMessages: (convId: string) => Promise<Message[]>;
  loadConversation: (convId: string) => Promise<UIMessage[]>;
  writeMessage: (m: Message) => void;
  writeToolCall: (tc: ToolCall) => void;
  getStats: () => Promise<{ lifetimeTokens: number; conversationCount: number; messageCount: number }>;
  openWorkspaceDialog: () => Promise<Workspace | null>;
  listWorkspaceFiles: (dirPath: string, query: string) => Promise<string[]>;
  readWorkspaceFile: (dirPath: string, filePath: string) => Promise<string>;
  loadStoredSession: () => Promise<StoredSession | null>;
  saveSession: (s: StoredSession) => Promise<void>;
  startOAuth: () => Promise<void>;
  signOut: () => Promise<void>;
  onSessionReceived: (cb: (s: StoredSession) => void) => () => void;
  fetchModels: (jwt: string) => Promise<Record<string, ModelDef>>;
  getBudget: (jwt: string) => Promise<BudgetInfo>;
  openSettings: () => void;
  spawnAgent: (config: AgentInitConfig) => Promise<void>;
  killAgent: (convId: string) => Promise<void>;
  onAgentPort: (cb: (convId: string) => void) => () => void;
  onAgentMessage: (convId: string, cb: (msg: AgentChunk) => void) => void;
  sendToAgent: (convId: string, msg: { type: 'send'; content: string } | { type: 'kill' }) => void;
  removeAgentPort: (convId: string) => void;
  onConvTitleUpdated: (cb: (convId: string, title: string) => void) => () => void;
  browserShow: (convId: string, bounds: { x: number; y: number; width: number; height: number }) => Promise<void>;
  browserHide: () => Promise<void>;
  browserSetBounds: (convId: string, bounds: { x: number; y: number; width: number; height: number }) => Promise<void>;
  browserNavigate: (convId: string, url: string) => Promise<void>;
  browserBack: (convId: string) => Promise<void>;
  browserForward: (convId: string) => Promise<void>;
  browserReload: (convId: string) => Promise<void>;
  browserStop: (convId: string) => Promise<void>;
  browserDestroy: (convId: string) => Promise<void>;
  browserFindInPage: (convId: string, text: string, opts?: { forward?: boolean; findNext?: boolean }) => Promise<void>;
  browserStopFind: (convId: string) => Promise<void>;
  onBrowserState: (cb: (state: { convId: string; url: string; title: string; loading: boolean; canGoBack: boolean; canGoForward: boolean }) => void) => () => void;
  ptyEnsure: (convId: string, cwd?: string) => Promise<void>;
  ptyAttach: (convId: string, cols: number, rows: number) => Promise<string>;
  ptyDetach: (convId: string) => Promise<void>;
  ptyWrite: (convId: string, data: string) => void;
  ptyResize: (convId: string, cols: number, rows: number) => Promise<void>;
  ptyKill: (convId: string) => Promise<void>;
  onPtyData: (convId: string, cb: (data: string) => void) => () => void;
  onPtyExit: (convId: string, cb: () => void) => void;
  onUpdateStatus: (cb: (status: string, info?: string) => void) => () => void;
  updateQuitAndInstall: () => void;
  updateOpenReleases: () => void;
  updateCheck: () => void;
};
declare global { interface Window { electron: ElectronAPI; } }
export type { ElectronAPI };
